### ISSUE TITLE
Timepicker (chronopic) is broken

### ISSUE THREAD

**Issue by cnrdh** [npolar/npdc-indicator#4]
Chronopic is broken now, triggers on created fields (shown disabled) but not for when field (timeseries)

Example https://data.npolar.no/indicator/timeseries/9846e987-8d2b-5e2c-9a40-f7d52b4b0822/edit

Maybe because when is a string in the schema

``` json
"when": {
"type": [
"string",
"null"
],
"pattern": "^[0-9]{4}"
},
```

``` js
app.directive('input', require('npdc-common/src/wrappers/chronopic')({
  css: { 'max-width': '340px' },
  format: '{date}' // display format (stored as proper RFC 3339 date or date-time)
}));
```

**Comment by baelter** [comment]
I'm going to reimplement chronopic integration later today.
